name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: archive
      run: xcodebuild -project Fire.xcodeproj/ -scheme Fire -archivePath ./archive -configuration Release
    - name: copy app && zip app && generate appcast
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: |
        mkdir apps
        cp -a ./build/Release/Fire.app apps
        ditto -c -k --sequesterRsrc --keepParent apps/Fire.app apps/Fire.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*
        ./bin/generate_appcast -s $sparkle_key ./apps/
