name: test

on:
  push:
    branch:
      - '**'
  pull_request:
    branch:
      - '**'

jobs:
  test:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install depencies
      run: pod install
    - name: archive
      run: xcodebuild archive -workspace Fire.xcworkspace -scheme Fire -archivePath ./archive-Fire -configuration Release
    - name: copy app && zip app && generate appcast
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: |
        mkdir apps
        cp -a ./archive-Fire.xcarchive/Products/Applications/*.app apps
        ditto -c -k --sequesterRsrc --keepParent apps/Fire.app apps/Fire.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*
        ./bin/generate_appcast -s $sparkle_key ./apps/
